ITEM.name = "AUG A3"
ITEM.description = "An automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_aug.mdl"
ITEM.class = "arccw_go_aug"
ITEM.weaponCategory = "rifle"
ITEM.width = 1
ITEM.height = 3
ITEM.weight = 12.75
ITEM.noBusiness = true