ITEM.name = "AN/M14 Thermite"
ITEM.description = "An explosive grenade containing thermite."
ITEM.model = "models/weapons/arccw_go/w_eq_incendiarygrenade_thrown.mdl"
ITEM.class = "arccw_go_nade_incendiary"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.5
ITEM.noBusiness = true
