ITEM.name = "Pheropods"
ITEM.description = "Glandular sacs recently harvested from the deceased body of an Antlion Guard."
ITEM.model = "models/weapons/w_bugbait.mdl"
ITEM.class = "weapon_bugbait"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.5
ITEM.noBusiness = true
