ITEM.name = "Binoculars"
ITEM.description = "Used to view an area from a distance."
ITEM.model = "models/weapons/w_binocularsbp.mdl"
ITEM.class = "weapon_rpw_binoculars"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.75
ITEM.noBusiness = true
