ITEM.name = "CZ-75"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_cz75.mdl"
ITEM.class = "arccw_go_cz75"
ITEM.weaponCategory = "pistol"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 3
ITEM.noBusiness = true
