ITEM.name = "G3"
ITEM.description = "An automatic rifle"
ITEM.model = "models/weapons/arccw_go/v_pist_fiveseven.mdl"
ITEM.class = "arccw_go_g3"
ITEM.weaponCategory = "rifle"
ITEM.width = 3
ITEM.height = 1
ITEM.weight = 13
ITEM.noBusiness = true
