ITEM.name = "M67 Frag"
ITEM.description = "An explosive grenade."
ITEM.model = "models/weapons/arccw_go/w_eq_fraggrenade_thrown.mdl"
ITEM.class = "arccw_go_nade_frag"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1.3
ITEM.noBusiness = true
