ITEM.name = "MP5A3"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_mp5.mdl"
ITEM.class = "arccw_go_mp5"
ITEM.weaponCategory = "smg"
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 9.5
ITEM.noBusiness = true
