ITEM.name = "Model 5210 Smoke"
ITEM.description = "A non-lethal grenade capable of creating a cloud of smoke."
ITEM.model = "models/weapons/arccw_go/w_eq_smokegrenade_thrown.mdl"
ITEM.class = "arccw_go_nade_smoke"
ITEM.weaponCategory = "utility"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1
ITEM.noBusiness = true
