ITEM.name = "ACE 22"
ITEM.description = "An automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_ace.mdl"
ITEM.class = "arccw_go_ace"
ITEM.weaponCategory = "rifle"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 10.25
ITEM.noBusiness = true