ITEM.name = "AR-15"
ITEM.description = "A semi-automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_car15.mdl"
ITEM.class = "arccw_go_ar15"
ITEM.weaponCategory = "rifle"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 9.75
ITEM.noBusiness = true