ITEM.name = "AWSM"
ITEM.description = "A sniper."
ITEM.model = "models/weapons/arccw_go/v_snip_awp.mdl"
ITEM.class = "arccw_go_awp"
ITEM.weaponCategory = "sniper"
ITEM.width = 4
ITEM.height = 2
ITEM.weight = 14
ITEM.noBusiness = true