ITEM.name = "AKM"
ITEM.description = "An automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_ak47.mdl"
ITEM.class = "arccw_go_ak47"
ITEM.weaponCategory = "rifle"
ITEM.width = 1
ITEM.height = 3
ITEM.weight = 11
ITEM.noBusiness = true