ITEM.name = "Desert Eagle"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_deagle.mdl"
ITEM.class = "arccw_go_deagle"
ITEM.weaponCategory = "pistol"
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 4.8
ITEM.noBusiness = true