ITEM.name = "Five-SeveN"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_fiveseven.mdl"
ITEM.class = "arccw_go_fiveseven"
ITEM.weaponCategory = "pistol"
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 2.75
ITEM.noBusiness = true