ITEM.name = "Glock 17"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_glock.mdl"
ITEM.class = "arccw_go_glock"
ITEM.weaponCategory = "pistol"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 4.25
ITEM.noBusiness = true