ITEM.name = "Model 870"
ITEM.description = "A shotgun"
ITEM.model = "models/weapons/arccw_go/v_shot_870.mdl"
ITEM.class = "arccw_go_870"
ITEM.weaponCategory = "shotgun"
ITEM.width = 3
ITEM.height = 1
ITEM.weight = 9
ITEM.noBusiness = true