ITEM.name = "M4A1"
ITEM.description = "An automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_m4a1.mdl"
ITEM.class = "arccw_go_m4"
ITEM.weaponCategory = "rifle"
ITEM.width = 1
ITEM.height = 3
ITEM.weight = 10.75
ITEM.noBusiness = true
