ITEM.name = "MP7A1"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_mp7.mdl"
ITEM.class = "arccw_go_mp7"
ITEM.weaponCategory = "smg"
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 7
ITEM.noBusiness = true
