ITEM.name = "M-10"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_mac10.mdl"
ITEM.class = "arccw_go_mac10"
ITEM.weaponCategory = "smg"
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 6.5
ITEM.noBusiness = true
