ITEM.name = "M92FS"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_m9.mdl"
ITEM.class = "arccw_go_m9"
ITEM.weaponCategory = "pistol"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 3.25
ITEM.noBusiness = true
