ITEM.name = "MAG-7"
ITEM.description = "A shotgun."
ITEM.model = "models/weapons/arccw_go/v_shot_mag7.mdl"
ITEM.class = "arccw_go_mag7"
ITEM.weaponCategory = "shotgun"
ITEM.width = 3
ITEM.height = 1
ITEM.weight = 10
ITEM.noBusiness = true
