ITEM.name = "PP-9 Bizon-2"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_bizon.mdl"
ITEM.class = "arccw_go_bizon"
ITEM.weaponCategory = "smg"
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 8.5
ITEM.noBusiness = true