ITEM.name = "P90 TR"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_p90.mdl"
ITEM.class = "arccw_go_p90"
ITEM.weaponCategory = "smg"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 8.25
ITEM.noBusiness = true
