ITEM.name = "P2000"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_p2000.mdl"
ITEM.class = "arccw_go_p2000"
ITEM.weaponCategory = "pistol"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 3.6
ITEM.noBusiness = true
