ITEM.name = "SuperNova"
ITEM.description = "A shotgun."
ITEM.model = "models/weapons/arccw_go/v_shot_nova.mdl"
ITEM.class = "arccw_go_nova"
ITEM.weaponCategory = "shotgun"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 7.25
ITEM.noBusiness = true