ITEM.name = "SIG SG556"
ITEM.description = "An automatic rifle."
ITEM.model = "models/weapons/arccw_go/v_rif_sg556.mdl"
ITEM.class = "arccw_go_sg556"
ITEM.weaponCategory = "rifle"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 11.25
ITEM.noBusiness = true
