ITEM.name = "SSG08"
ITEM.description = "A sniper."
ITEM.model = "models/weapons/arccw_go/v_snip_ssg08.mdl"
ITEM.class = "arccw_go_ssg08"
ITEM.weaponCategory = "sniper"
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 8.5
ITEM.noBusiness = true
