ITEM.name = "TEC-9"
ITEM.description = "A semi-automatic pistol."
ITEM.model = "models/weapons/arccw_go/v_pist_tec9.mdl"
ITEM.class = "arccw_go_tec9"
ITEM.weaponCategory = "pistol"
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 4.5
ITEM.noBusiness = true