ITEM.name = "UMP-45"
ITEM.description = "A submachine gun."
ITEM.model = "models/weapons/arccw_go/v_smg_ump45.mdl"
ITEM.class = "arccw_go_ump"
ITEM.weaponCategory = "smg"
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 8.75
ITEM.noBusiness = true